<?php
	if ( ! defined( 'ABSPATH' ) ) {
		exit; // Exit if accessed directly
	} ?>
    <div class="abtb_doc_panel" data-tabs="#abptb_pdf">
        <div class="abtb_doc_page_head">
            <h2>📄 PDF Configuration</h2>
            <p class="abtb_doc_lede">
                Manage PDF-related settings from a single place. These options allow you to customize PDF appearance,
                branding, colors, ticket download permissions, and Terms &amp; Conditions content for documents
                generated by Transport Booking.
            </p>
        </div>

        <h3>⚙️ Options</h3>
        <table>
            <thead>
                <tr>
                    <th>Option</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>PDF Background Image</strong></td>
                    <td>Optionally add a custom background image or watermark layer to PDF pages to enhance their visual appearance and reinforce your brand identity.</td>
                </tr>
                <tr>
                    <td><strong>PDF Logo</strong></td>
                    <td>Upload or select a custom logo image to display in the header of generated PDF documents and provide consistent branding across your downloadable documents.</td>
                </tr>
                <tr>
                    <td><strong>User Role for Ticket Download</strong></td>
                    <td>Choose the WordPress user roles that are permitted to download transport tickets. Only users with the selected roles can access the ticket download functionality.</td>
                </tr>
                <tr>
                    <td><strong>PDF Logo Height</strong></td>
                    <td>Define the maximum height of the PDF logo in pixels (px) to ensure proper sizing and layout within generated PDF documents.</td>
                </tr>
                <tr>
                    <td><strong>Background Color</strong></td>
                    <td>Choose a custom background color for the PDF canvas to match your brand identity and maintain a consistent document appearance.</td>
                </tr>
                <tr>
                    <td><strong>Text Color</strong></td>
                    <td>Set the primary text color used for typography inside PDF documents to maintain readability and visual consistency.</td>
                </tr>
                <tr>
                    <td><strong>Terms &amp; Conditions Title</strong></td>
                    <td>Enter a custom heading for the Terms &amp; Conditions section that is displayed in the footer area of generated PDF documents.</td>
                </tr>
                <tr>
                    <td><strong>Terms &amp; Conditions Text</strong></td>
                    <td>Provide the detailed terms, policies, disclaimers, or other legal information displayed in the Terms &amp; Conditions section of generated PDF documents.</td>
                </tr>
            </tbody>
        </table>

        <div class="abtb_doc_callout abtb_doc_callout_tip">
            <strong>💡 Consistent branding</strong>
            Upload a logo and set your brand colors and background image before generating tickets, so every PDF
            document reflects your identity from the start.
        </div>

        <div class="abtb_doc_screen" data-abtb-doc-img="<?php echo esc_url( ABPTB_DOC_URL . '/' ) ?>image/pdf.png"><img class="abtb_doc_screen_img" src="#" alt="PDF Configuration"></div>
    </div>
<?php
