<?php
	if ( ! defined( 'ABSPATH' ) ) {
		exit; // Exit if accessed directly
	} ?>
    <div class="tab_item" data-tabs="#abptb_pdf">
        <h2 class="abp_color_theme">📄 PDF Configuration</h2>
        <div class="_divider"></div>
        <i class="_color_7_fs_label_mar_tb_d_block">Manage PDF-related settings from a single place. These options allow you to customize PDF appearance, branding, colors, ticket download permissions, and Terms & Conditions content for documents generated by Transport Booking.</i>
        <table class="abp_fixed_text_left_mt">
            <tbody>
            <tr>
                <th class="_color_theme">PDF Background Image</th>
                <td colspan="3">Optionally add a custom background image or watermark layer to PDF pages to enhance their visual appearance and reinforce your brand identity.</td>
            </tr>
            <tr>
                <th class="_color_theme">PDF Logo</th>
                <td colspan="3">Upload or select a custom logo image to display in the header of generated PDF documents and provide consistent branding across your downloadable documents.</td>
            </tr>
            <tr>
                <th class="_color_theme">User Role for Ticket Download</th>
                <td colspan="3">Choose the WordPress user roles that are permitted to download transport tickets. Only users with the selected roles will be allowed to access ticket download functionality.</td>
            </tr>
            <tr>
                <th class="_color_theme">PDF Logo Height</th>
                <td colspan="3">Define the maximum height of the PDF logo in pixels (px) to ensure proper sizing and layout within generated PDF documents.</td>
            </tr>
            <tr>
                <th class="_color_theme">Background Color</th>
                <td colspan="3">Choose a custom background color for the PDF canvas to match your brand identity and maintain a consistent document appearance.</td>
            </tr>
            <tr>
                <th class="_color_theme">Text Color</th>
                <td colspan="3">Set the primary text color used for typography inside PDF documents to maintain readability and visual consistency.</td>
            </tr>
            <tr>
                <th class="_color_theme">Terms & Conditions Title</th>
                <td colspan="3">Enter a custom heading for the Terms & Conditions section that will be displayed in the footer area of generated PDF documents.</td>
            </tr>
            <tr>
                <th class="_color_theme">Terms & Conditions Text</th>
                <td colspan="3">Provide the detailed terms, policies, disclaimers, or other legal information that will be displayed in the Terms & Conditions section of generated PDF documents.</td>
            </tr>
            </tbody>
        </table>
        <div class="_mar_tb" data-image-href="<?php echo esc_url( ABPTB_DOC_URL . '/' ) ?>image/pdf.png"><img class="_img_control" src="#" alt="PDF Configuration"></div>
    </div>
<?php
